In [12]:
import os
import pandas
import urllib.request

# 1. Exploración y comprensión de los datos

## 1.1. Descargar

In [13]:
filename = "main.csv"
if not os.path.exists(filename):
  urllib.request.urlretrieve("https://data.nasa.gov/docs/legacy/meteorite_landings/Meteorite_Landings.csv", filename)
dataFrame = pandas.read_csv(filename)

## 1.2. Verificar

In [14]:
dataFrame.head()

,name,id,nametype,recclass,mass (g),fall,year,reclat,reclong,GeoLocation
0,Aachen,1,Valid,L5,21.0,Fell,1880.0,50.77500,6.08333,"(50.775, 6.08333)"
1,Aarhus,2,Valid,H6,720.0,Fell,1951.0,56.18333,10.23333,"(56.18333, 10.23333)"
2,Abee,6,Valid,EH4,107000.0,Fell,1952.0,54.21667,-113.00000,"(54.21667, -113.0)"
3,Acapulco,10,Valid,Acapulcoite,1914.0,Fell,1976.0,16.88333,-99.90000,"(16.88333, -99.9)"
4,Achiras,370,Valid,L6,780.0,Fell,1902.0,-33.16667,-64.95000,"(-33.16667, -64.95)"

In [15]:
dataFrame.tail()

,name,id,nametype,recclass,mass (g),fall,year,reclat,reclong,GeoLocation
45711,Zillah 002,31356,Valid,Eucrite,172.0,Found,1990.0,29.03700,17.01850,"(29.037, 17.0185)"
45712,Zinder,30409,Valid,"Pallasite, ungrouped",46.0,Found,1999.0,13.78333,8.96667,"(13.78333, 8.96667)"
45713,Zlin,30410,Valid,H4,3.3,Found,1939.0,49.25000,17.66667,"(49.25, 17.66667)"
45714,Zubkovsky,31357,Valid,L6,2167.0,Found,2003.0,49.78917,41.50460,"(49.78917, 41.5046)"
45715,Zulu Queen,30414,Valid,L3.7,200.0,Found,1976.0,33.98333,-115.68333,"(33.98333, -115.68333)"

## 1.3. Explorar

In [16]:
print("Tamaño")
print(dataFrame.size)

Tamaño
457160

In [17]:
print("Tipos de información")
print(dataFrame.dtypes)

Tipos de información
name               str
id               int64
nametype           str
recclass           str
mass (g)       float64
fall               str
year           float64
reclat         float64
reclong        float64
GeoLocation        str
dtype: object

In [20]:
print("Datos duplicados")
print(dataFrame.duplicated().sum())

Datos duplicados
0

In [21]:
print("Valores faltantes")
print(dataFrame.isnull().sum())

Valores faltantes
name              0
id                0
nametype          0
recclass          0
mass (g)        131
fall              0
year            291
reclat         7315
reclong        7315
GeoLocation    7315
dtype: int64